/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ticketmachine;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ezbishal
 */

public class MovieSelection extends javax.swing.JFrame {
    
    public static String selectedMovie;
    

    /**
     * Creates new form Dashboard
     */
    public MovieSelection() {
        
        
        initComponents();
        
        genreList.setEnabled(false);
        
        String[] genre = Reader.genreReader().toArray(new String[0]);
        genreList.setModel(new DefaultComboBoxModel(genre));
        genreList.setSelectedItem(null);
        
        genreList.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                String genre = (String) genreList.getSelectedItem();
                String[] movies = Reader.moviesReader(genre).toArray(new String[0]);
                moviesList.setModel(new DefaultComboBoxModel(movies));
                moviesList.setSelectedItem(null);
                
                 ImageIcon imageIcon = new ImageIcon("Cinema.png");
                Image image = imageIcon.getImage();
                Image imageScale = image.getScaledInstance(picLabel.getWidth(),picLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(imageScale);
                picLabel.setIcon(scaledIcon);
            }
        });
        
        moviesList.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                ImageIcon imageIcon = new ImageIcon(Reader.imageReader((String) moviesList.getSelectedItem()));
                Image image = imageIcon.getImage();
                Image imageScale = image.getScaledInstance(picLabel.getWidth(),picLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(imageScale);
                picLabel.setIcon(scaledIcon);
            }
        });
        
        String[] movies = Reader.moviesReader().toArray(new String[0]);
        moviesList.setModel(new DefaultComboBoxModel(movies));
        moviesList.setSelectedItem(null);
     
                ImageIcon imageIcon = new ImageIcon("Cinema.png");
                Image image = imageIcon.getImage();
                Image imageScale = image.getScaledInstance(picLabel.getWidth(),picLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(imageScale);
                picLabel.setIcon(scaledIcon);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        ticketMachineLabel = new javax.swing.JLabel();
        moviesLabel1 = new javax.swing.JLabel();
        moviesList = new javax.swing.JComboBox<>();
        purchaseButton = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        checkBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        genreList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genreList.setSelectedIndex(-1);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        ticketMachineLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ticketMachineLabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketMachineLabel.setText("         Movie Selection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(ticketMachineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ticketMachineLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        moviesLabel1.setText("Select a movie");

        moviesList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        moviesList.setSelectedIndex(-1);
        moviesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesListActionPerformed(evt);
            }
        });

        purchaseButton.setText("Purchase Tickets");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        checkBox.setText("Select By Genre");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moviesList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(genreList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moviesLabel1))
                .addGap(35, 35, 35)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moviesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moviesList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(checkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genreList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(purchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moviesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moviesListActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
        
        selectedMovie = (String) moviesList.getSelectedItem();
        
        if(selectedMovie != null){
         
        dispose();       
        TicketPurchase ticketMachine = new TicketPurchase();
        ticketMachine.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select a movie!",
                                   "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        // TODO add your handling code here:
        if(checkBox.isSelected()){
            genreList.setEnabled(true);
        }
        else {
            genreList.setEnabled(false);
            String[] movies = Reader.moviesReader().toArray(new String[0]);
            moviesList.setModel(new DefaultComboBoxModel(movies));
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JComboBox<String> genreList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moviesLabel1;
    private javax.swing.JComboBox<String> moviesList;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JLabel ticketMachineLabel;
    // End of variables declaration//GEN-END:variables
}
